Update prop-types to 15.5.10
nkbt/react-height pull request #37
Opened 2018-03-15 11:35 UTC by leonidsheremeto

Hello. 

Using your library we have a warning "Calling PropTypes validators directly is not supported by the `prop-types`"

This question has already been discussed here: https://github.com/malte-wessel/react-custom-scrollbars/issues/153 and people advice to update prop-types to 15.5.10

Thank you.

2018-03-21 16:18 UTC, elyashenko approved these changes

2018-04-05 16:19 UTC, LeoIannacone commented
Hi, can you please merge this ?

2018-04-06 00:26 UTC, nkbt requested changes

2018-04-06 00:26 UTC, nkbt commented on package.json
> +    "prop-types": "15.5.10"
would be better to use `^15.5.8`, which is `15.5.10` compatible and also will not change the "base" version

2018-04-08 01:20 UTC, nkbt approved these changes

2018-04-08 01:20 UTC, merged

2019-04-10 11:44 UTC, Ektoplasme commented
Still on 15.5.8 too